### PR TITLE
Fixes #14

### LINKED ISSUE #14: Animated Logo for Custom Load Screen
Introduction: We take great pride in the small details at MyBit. This is why we need a custom load screen animation created and implemented for the MyBit Decentralised Development Fund (DDF) and MyBit Go. 

Requirements: This should be an animation of the MyBit Logo that replaces the standard loading "circle." It needs to be Implemented on MyBit Go and the DDF so two separate pull requests are required to complete this task after the animated design has been approved.

Resources:
https://files.mybit.io/files/

Expected Deliverables: Source files and integration into MyBit Go and DDF via 2 separate pull requests.

Additional Information:
The design process often involves multiple iterations. Therefore, please do not expect the task to be closed after the first version is submitted. We do understand the value of every contributors time, which is why we strive to make the task descriptions as detailed as possible. If you are unsure about a specific detail or have any questions please feel free to ask prior to starting or during the process.

Disclaimer: 
All work completed via the MyBit Decentralised Development Fund is property of the MyBit Foundation (CHE-177.186.963) and may be used, re-used, and/or distributed, re-distributed by the MyBit Foundation for financial gain. The contributor holds no warrant nor claims for any future payments resulting from monetisation schemes originating from the MyBit Foundation or any of its affiliates. Where law permits outside of open source regulations, the contributor is not permitted to distribute any work completed via the MyBit Decentralised Development Fund (DDF) for personal gain.

### PR DESCRIPTION
**Pull request by uivlis**
Put up link for animation logo

### CODE REVIEW

**Comment by 0xjjpa** [comment]
👋 @uivlis looks great! One thing that we weren't too keen about it is that it modifies the shape of the logo, which we would prefer to avoid. We were thinking about a slow draw of the outline of the logo as an option, similar to [this](https://codepen.io/jjperezaguinaga/pen/mApqz). What do you think? You could use [Vivus](https://maxwellito.github.io/vivus/) or something similar to give that a try ☺️

**Comment by uivlis** [comment]
How about this https://codepen.io/uivlis/pen/OBBdBJ ?

**Comment by 0xjjpa** [comment]
@uivlis We liked the previous one more! We really looking for something animated around the outline of the logo. Let me know if you need some inspiration ☺️

**Comment by uivlis** [comment]
Oh ok, I'll try something with the outline. The problem is, obtaining the outline from the logo is not something trivial in order for the animation with vivus.js to succeed. Perhaps you could supply me with the outline logo (not present in the public brand kit), or, if not, I'll try make do with what I can.

**Comment by 0xjjpa** [comment]
@uivlis We can! Hold on a second ☺️

**Comment by 0xjjpa** [comment]
Give this a try ☺️ 
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="100%" height="100%" viewBox="0 0 512 512" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:1.41421;">
    <g transform="matrix(0.783612,0,0,0.802351,55.3953,50.5942)">
        <path d="M510.35,256L415,351.42L414.83,351.42C374,310.76 318,285.5 256,285.5C194,285.5 137.91,310.76 97.07,351.42L96.9,351.42L1.65,256L256,1.65L510.35,256Z" style="fill:none;stroke:black;stroke-width:1.26px;"/>
    </g>
    <g transform="matrix(0.783612,0,0,0.802351,55.3953,50.5942)">
        <path d="M386.86,379.54L256.09,510.31L125.15,379.54C159.714,344.657 206.893,325.097 256,325.29C264.748,325.276 273.486,325.878 282.15,327.09C321.849,332.631 358.649,351.064 386.86,379.54Z" style="fill:none;stroke:black;stroke-width:1.26px;"/>
    </g>
</svg>
```

**Comment by uivlis** [comment]
https://codepen.io/uivlis/pen/aRXQgj, maybe?

**Comment by 0xjjpa** [comment]
@uivlis Way better! Let me get some internal feedback and get back to you ☺️

**Comment by 0xjjpa** [comment]
@uivlis We like it! Could you add a fill effect at the end for each fragment of the logo, and then the full vanish?

**Comment by uivlis** [comment]
https://codepen.io/uivlis/pen/aRXQgj

**Comment by 0xjjpa** [comment]
Looks way better! Could you ensure that both fills are at the same time, and the fade out is a bit slower? Currently it's a bit too fast.

**Comment by uivlis** [comment]
https://codepen.io/uivlis/pen/aRXQgj

**Comment by ghost** [comment]
Nice one @uivlis

**Comment by 0xjjpa** [comment]
Awesome, we'll keep that one ☺️

**Pull request merged**
